services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app # For development: Mount current directory to container
      - /app/node_modules # Exclude node_modules from host volume mount
    environment:
      - NODE_ENV=development # Set to 'production' for production
