services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    # No volumes in prod! (keeps the built .next inside the image)
    # No NODE_ENV override here; it's set in the image to "production"
